from django.conf.urls import url
from .views import *

urlpatterns = [
	url(r'^$', index),
	#url(r'^(\d+)/$',detail),
	#url(r'^delete(\d+)$',delete),
	#url(r'^create$',create),
	#url(r'^area/(\d+)/$',area),
	#url(r'^get/$',get),
	#url(r'^post_index/$',post_index),
	#url(r'^post_b/$',post_b),
	#url(r'^redirect/$',redirect),
	#url(r'^ajax_index/$',ajax_index),
	#url(r'^json_data/$',json_data),
	#url(r'^cookie_set/$',cookie_set),
	#url(r'^cookie_get/$',cookie_get),
	#url(r'^test_cookie/',test_cookie),
	# url(r'^get_cookie/',get_cookie),
	# url(r'^delete_cookie/',delete_cookie),
	# url(r'^session_test/$',session_test),
	# url(r'^get_session/',get_session),
	# url(r'^session_test2/$',session_test2),
	# url(r'^session_del/',del_session),
	# url(r'^session_read/$',session_read),
	# url(r'^clear_session/$',clear_session),
	# url(r'^flush_session/$',flush_session),
	# url(r'^redis_session/$',redis_session),
	url(r'^book/$',book,name='book'),
	# url(r'^getcookie',getcookie),
	url(r'^session1/$',session1),
	url(r'^session2/$',session2),
	url(r'^session2_handle/$',session2_handle),
	url(r'^session3/$',session3),
	url(r'^static_test/$',static_test),
	url(r'^pic_upload/$', pic_upload),
	# 定义一个url 匹配规则，如果请求是127.0.0.1:8000/pic_handle/，那么就交给views 文件的pic_handle 函数处理
	url(r'^pic_handle/$', pic_handle),
	url(r'^show_pic/$',show_pic),
	url(r'^editor/$',editor),
	url(r'^show/$',show),
	url(r'^send_mail/$',send_mail),
	url(r'^verify_code/$',verify_code),
	url(r'^verify_show/$',verify_show),
	url(r'^verify_yz/$',verify_yz),
	url(r'^page(?P<pnum>\d*)/$',page_test),
	url(r'^cengjixuanze/$',cengjixuanze),
	url(r'^TuShu/$',TuShu),
	url(r'^RenWu(\d+)/$',RenWu),
	url(r'^areainfo_page(?P<pindex>\d*)/$',areainfo_page),
	url(r'^area1/$',area1),
	url(r'^area2/$',area2),
	url(r'^area3_(\d+)/$',area3)
 ]
